# Generated by Django 3.2.11 on 2022-02-14 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provincia',
            name='departamento',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='erp.departamento', verbose_name='Departamento'),
            preserve_default=False,
        ),
    ]
