# Generated by Django 3.2.11 on 2022-02-23 14:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metro', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Mtr2')),
                ('metro_prom', models.IntegerField(verbose_name='Mtr2 Promedio')),
                ('pre_contado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Contado')),
                ('pre_financiado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Financiado')),
                ('state', models.CharField(choices=[('Pagado', 'PAGADO'), ('Pendiente', 'PENDIENTE')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('date_creation', models.DateTimeField(auto_now=True)),
                ('date_uptated', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plano_lote', to='erp.plano', verbose_name='Lote')),
                ('mz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plano_mz', to='erp.plano', verbose_name='Mz')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventario',
                'ordering': ['id'],
            },
        ),
    ]
