# Generated by Django 3.2.11 on 2022-02-25 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_inventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detpago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuota', models.IntegerField(verbose_name='Nro Couta')),
                ('date_pago', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Pago')),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto')),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo')),
                ('state', models.CharField(choices=[('Pagado', 'PAGADO'), ('Pendiente', 'PENDIENTE')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Detallepago',
                'verbose_name_plural': 'DetallePagos',
                'db_table': 'detpago',
                'ordering': ['id'],
            },
        ),
    ]
