# Generated by Django 3.2.11 on 2022-02-14 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_provincia_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='distrito',
            name='departamento',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='erp.departamento', verbose_name='Departamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='erp.provincia', verbose_name='Provincia'),
            preserve_default=False,
        ),
    ]
