# Generated by Django 3.2.11 on 2022-03-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_alter_inventario_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='movilidad',
            field=models.CharField(choices=[('Sin movilidad', 'SIN MOVILIDAD'), ('Con movilidad', 'CON MOVILIDAD')], default=2, max_length=15, verbose_name='Movilidad'),
            preserve_default=False,
        ),
    ]
