# Generated by Django 3.2.11 on 2022-02-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_alter_empleado_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='horario',
            field=models.CharField(default=2, max_length=150, verbose_name='Horario'),
            preserve_default=False,
        ),
    ]
