# Generated by Django 3.2.11 on 2022-02-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_detpago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='state_civil',
            field=models.CharField(choices=[('Soltero', 'SOLTERO'), ('Casado', 'CASADO'), ('Viudo', 'VIUDO'), ('Divorciado', 'DIVORCIADO')], max_length=50, verbose_name='Estado Civil'),
        ),
    ]
