# Generated by Django 3.2.11 on 2022-02-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_cliente_state_civil'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='especialidad',
            field=models.CharField(default=2, max_length=150, verbose_name='Especialidad/Ocupación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='names',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apellidos',
            field=models.CharField(max_length=150, unique=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='names',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre'),
        ),
    ]
