# Generated by Django 3.2.11 on 2022-02-08 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_puesto_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.area', verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.CharField(max_length=8, unique=True, verbose_name='Dni'),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.area', verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
