# Generated by Django 3.2.11 on 2022-03-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='hora_ingreso',
            field=models.DateTimeField(auto_now=True, verbose_name='Hora de ingreso'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='hora_salida',
            field=models.DateTimeField(auto_now=True, verbose_name='Hora de salida'),
        ),
    ]
