# Generated by Django 3.2.11 on 2022-03-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_auto_20220309_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='hora_ingreso',
            field=models.CharField(max_length=30, verbose_name='Hora de ingreso'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='hora_salida',
            field=models.CharField(max_length=30, verbose_name='Hora de salida'),
        ),
    ]
