# Generated by Django 3.2.11 on 2022-02-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_auto_20220228_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cellphone',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción'),
        ),
    ]
