# Generated by Django 3.2.11 on 2022-02-15 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_alter_agenda_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.empleado', verbose_name='Asesor Campo'),
        ),
    ]
