# Generated by Django 3.2.11 on 2022-03-09 21:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_auto_20220309_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.FileField(blank=True, max_length=40, null=True, upload_to='factura/%Y/%m/%d', verbose_name='Documento')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('date_creation', models.DateTimeField(auto_now=True)),
                ('date_uptated', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Contabilidad',
                'verbose_name_plural': 'Contabilidad',
                'db_table': 'contabilidad',
                'ordering': ['id'],
            },
        ),
    ]
