# Generated by Django 3.2.11 on 2022-02-15 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_alter_agenda_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='empleado',
        ),
        migrations.AddField(
            model_name='agenda',
            name='asesor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='empleado_asesor', to='erp.empleado', verbose_name='Asesor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agenda',
            name='lider',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='empleado_lider', to='erp.empleado', verbose_name='Líder'),
            preserve_default=False,
        ),
    ]
