# Generated by Django 3.2.11 on 2022-03-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_contabilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabilidad',
            name='factura10',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura10/%Y/%m/%d', verbose_name='10ma CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura11',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura11/%Y/%m/%d', verbose_name='11va CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura12',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura12/%Y/%m/%d', verbose_name='12va CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura13',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura13/%Y/%m/%d', verbose_name='13VA CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura14',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura14/%Y/%m/%d', verbose_name='14va CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura15',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura15/%Y/%m/%d', verbose_name='15va CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura16',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura16/%Y/%m/%d', verbose_name='16va CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura17',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura17/%Y/%m/%d', verbose_name='17va CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura18',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura18/%Y/%m/%d', verbose_name='18va CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura19',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura19/%Y/%m/%d', verbose_name='19va CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura2',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura2/%Y/%m/%d', verbose_name='2da CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura20',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura20/%Y/%m/%d', verbose_name='20va CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura21',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura21/%Y/%m/%d', verbose_name='21va CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura22',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura22/%Y/%m/%d', verbose_name='22va CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura23',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura23/%Y/%m/%d', verbose_name='23va CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura24',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura24/%Y/%m/%d', verbose_name='24va CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura25',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura25/%Y/%m/%d', verbose_name='25va CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura26',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura26/%Y/%m/%d', verbose_name='26va CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura27',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura27/%Y/%m/%d', verbose_name='27va CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura28',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura28/%Y/%m/%d', verbose_name='28va CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura29',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura29/%Y/%m/%d', verbose_name='29va CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura3',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura3/%Y/%m/%d', verbose_name='3ra CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura30',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura30/%Y/%m/%d', verbose_name='30va CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura31',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura31/%Y/%m/%d', verbose_name='31va CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura32',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura32/%Y/%m/%d', verbose_name='32va CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura33',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura33/%Y/%m/%d', verbose_name='33va CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura34',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura34/%Y/%m/%d', verbose_name='34va CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura35',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura35/%Y/%m/%d', verbose_name='35va CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura36',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura36/%Y/%m/%d', verbose_name='36va CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura37',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura37/%Y/%m/%d', verbose_name='37va CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura38',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura38/%Y/%m/%d', verbose_name='38va CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura39',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura39/%Y/%m/%d', verbose_name='39va CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura4',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura4/%Y/%m/%d', verbose_name='4ta CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura40',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura40/%Y/%m/%d', verbose_name='40va CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura5',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura5/%Y/%m/%d', verbose_name='5ta CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura6',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura6/%Y/%m/%d', verbose_name='6ta CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura7',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura7/%Y/%m/%d', verbose_name='7ma CUOTA'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura8',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura8/%Y/%m/%d', verbose_name='8va Cuota'),
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='factura9',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura9/%Y/%m/%d', verbose_name='9na CUOTA'),
        ),
        migrations.AlterField(
            model_name='contabilidad',
            name='factura',
            field=models.FileField(blank=True, max_length=40, null=True, upload_to='factura/%Y/%m/%d', verbose_name='1era CUOTA'),
        ),
    ]
