# Generated by Django 3.2.11 on 2022-02-15 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_auto_20220215_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='asesor_ca',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='empleado_asesor_ca', to='erp.empleado', verbose_name='Asesor Campo'),
            preserve_default=False,
        ),
    ]
