# Generated by Django 3.2.11 on 2022-02-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_agenda_asesor_ca'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='gender',
            field=models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino')], default='male', max_length=10, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='type',
            field=models.CharField(choices=[('propio', 'Propio'), ('externo', 'Externo')], default=2, max_length=10, verbose_name='Tipo de proyecto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='total_lote',
            field=models.IntegerField(default=0, verbose_name='Total de lotes'),
        ),
    ]
