# Generated by Django 3.2.11 on 2022-02-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_auto_20220215_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='gender',
        ),
    ]
