# Generated by Django 3.2.11 on 2022-02-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_remove_proyecto_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
