# Generated by Django 3.2.11 on 2022-02-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_alter_plano_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='age',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Edad'),
        ),
    ]
