# Generated by Django 3.2.11 on 2022-02-16 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_alter_reserva_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['id'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='proyecto',
        ),
    ]
