# Generated by Django 3.2.11 on 2022-02-16 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_auto_20220216_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='proyecto',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='erp.proyecto'),
            preserve_default=False,
        ),
    ]
