# Generated by Django 3.2.11 on 2022-02-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_reserva_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
