# Generated by Django 3.2.11 on 2022-02-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_alter_empleado_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='age',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Edad'),
        ),
    ]
