# Generated by Django 3.2.11 on 2022-02-17 21:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_alter_empleado_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio')),
                ('inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Inicial')),
                ('monto_frac', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Fraccionado')),
                ('cuota', models.IntegerField(default=0, verbose_name='Nro Cuota')),
                ('plazo', models.CharField(max_length=10, verbose_name='Plazo')),
                ('interes', models.CharField(choices=[('SIN INTERES', 'SIN INTERES'), ('CON INTERES', 'CON INTERES')], default='SIN INTERES', max_length=20, verbose_name='Interés')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('date_creation', models.DateTimeField(auto_now=True)),
                ('date_uptated', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.cliente', verbose_name='Cliente')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pago',
                'ordering': ['id'],
            },
        ),
    ]
